services:
  app1:
    build: .
    container_name: app1
    expose:
      - 8080
    volumes:
      - .:/app
    environment:
      - PORT=8080

  app2:
    build: .
    container_name: app2
    expose:
      - 8080
    volumes:
      - .:/app
    environment:
      - PORT=8080

  app3:
    build: .
    container_name: app3
    expose:
      - 8080
    volumes:
      - .:/app
    environment:
      - PORT=8080

  app4:
    build: .
    container_name: app4
    expose:
      - 8080
    volumes:
      - .:/app
    environment:
      - PORT=8080

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "6080:80"
    depends_on:
      - app1
      - app2
      - app3